export default [
    { name: 'Clothing & Fashion',
        value: 'CF' }, 
    { name: 'Toys',
        value: 'To' },
    { name: 'Electronics',
    value: 'EL' },
    { name: 'Furniture',
    value: 'FU' },
    { name: 'Books',
    value: 'BO' },
    { name: 'Craft',
    value: 'CR' },
    { name: 'Others',
    value: 'OT' },
];